### ISSUE TITLE
Research a randomizing algorithm for Commons, Uncommons, Rares, and Mythics.

### ISSUE THREAD

**Issue by kellydunn** [flp/cuddly-quack#7]
There's a few randomizing considerations to make with how a pack is randomized.  Keep in mind this list may be larger, but this is gathered from my personal experience, and hearing about it from other players in the community:
- Aside from getting a foil in a pack, it's generally thought that players will not receive two of the same card in the pack.
- There are typically 3-5 mythics per "booster box", and they usually take a rare slot in the pack (read unless they're foil).  
- Boosters usually contain 10 commons, 3 uncommons, a rare (or mythic), a basic land card, and a token for a total of 16 cards.  The basic land card and token are usualy discarded, for a total of 14 total cards to choose from.  MTGO typically leaves the basic land in, but I'm not sure if we care about that too much.  
- It should be noted that these numbers [have changed over time](http://mtgsalvation.gamepedia.com/Booster_pack)

Acceptance criteria:
- [x] Have a clear idea of how to randomly generate a pack given a set

**Comment by flp** [comment]
**Foils and mythics**

Foils, and mythics in particular, only occur in recent sets. Here are rules we've found concerning their rarity:
- A foil, if it exists in a booster, takes the place of a common.
- There is a 1/12 chance of getting a foil common, 1/18 a foil uncommon, and 1/36 a foil rare.
- There can not be more than one foil in a single pack.
- There is a 1/8 chance of a rare being a mythic rare.
- Mythic foils appear to be somewhat of an exception, because there are multiple sources online that say that there is a 1/216 chance of getting a mythic foil in a pack, which does not match the math. I think we should go with the 1/216 figure since many people seem to agree on it.

links for reference
foils - http://www.starcitygames.com/php/news/print.php?Article=17092
mythics - http://mtgsalvation.gamepedia.com/Print_sheet

**Comment by flp** [comment]
I'll open a new issue for adding foils in packs.
